"""empty message

Revision ID: 8f2f7f859a46
Revises: 05b7f3644c82
Create Date: 2017-12-20 14:45:38.452082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f2f7f859a46'
down_revision = '05b7f3644c82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idc', table_name='hosts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idc', 'hosts', ['idc'], unique=True)
    # ### end Alembic commands ###
